SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;

DELETE FROM CanHo_TienIch WHERE CanHoId IN (SELECT Id FROM CanHo WHERE TieuDe LIKE 'TEST E2E%');
DELETE FROM AnhCanHo WHERE CanHoId IN (SELECT Id FROM CanHo WHERE TieuDe LIKE 'TEST E2E%');
DELETE FROM YeuThich WHERE CanHoId IN (SELECT Id FROM CanHo WHERE TieuDe LIKE 'TEST E2E%');
DELETE FROM LichXemNha WHERE CanHoId IN (SELECT Id FROM CanHo WHERE TieuDe LIKE 'TEST E2E%');
DELETE FROM CanHo WHERE TieuDe LIKE 'TEST E2E%';

-- Cũng dọn user E2E đăng ký test
DELETE FROM NguoiDung_VaiTro WHERE NguoiDungId IN (SELECT Id FROM NguoiDung WHERE Email LIKE 'e2e_user_%');
DELETE FROM NguoiDung WHERE Email LIKE 'e2e_user_%';

SELECT 'CanHo TEST E2E con lai' AS Loai, COUNT(*) AS So FROM CanHo WHERE TieuDe LIKE 'TEST E2E%'
UNION ALL
SELECT 'User E2E con lai', COUNT(*) FROM NguoiDung WHERE Email LIKE 'e2e_user_%';
